# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_t-x0bfDwW-U4lfhHTbOFfavJ5ab-6W
"""

"""
CodeAlpha Data Analytics Internship
Task 1: Web Scraping
Target site: http://books.toscrape.com  (built for scraping practice, fully legal)

What this script does:
1. Loops through all 50 pages of the catalogue (1000 books total)
2. For each book, extracts: Title, Price (£), Availability, Star Rating, Category
3. Saves everything into a clean CSV: books_data.csv

Run this yourself (needs internet access, e.g. locally or Google Colab):
    pip install requests beautifulsoup4 pandas
    python task1_web_scraping.py
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE_URL = "http://books.toscrape.com/catalogue/page-{}.html"
CATEGORY_BASE = "http://books.toscrape.com/"

RATING_MAP = {
    "One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5
}


def get_book_category(book_url):
    """Visit an individual book page to grab its category (breadcrumb)."""
    try:
        resp = requests.get(book_url, timeout=10)
        soup = BeautifulSoup(resp.text, "html.parser")
        breadcrumb = soup.select("ul.breadcrumb li a")
        # breadcrumb[0] = Home, breadcrumb[1] = Category, breadcrumb[2] = Book title
        return breadcrumb[2].text.strip() if len(breadcrumb) >= 3 else "Unknown"
    except Exception:
        return "Unknown"


def scrape_all_books(fetch_category=True, max_pages=50):
    all_books = []

    for page in range(1, max_pages + 1):
        url = BASE_URL.format(page)
        response = requests.get(url, timeout=10)
        if response.status_code != 200:
            print(f"Page {page} not found, stopping.")
            break

        soup = BeautifulSoup(response.text, "html.parser")
        articles = soup.select("article.product_pod")

        for article in articles:
            title = article.h3.a["title"]
            price_text = article.select_one("p.price_color").text.strip()
            price = float(price_text.replace("£", "").replace("Â", ""))
            availability = article.select_one("p.instock.availability").text.strip()
            rating_class = article.select_one("p.star-rating")["class"][1]
            rating = RATING_MAP.get(rating_class, 0)

            relative_link = article.h3.a["href"].replace("../../../", "")
            book_url = CATEGORY_BASE + "catalogue/" + relative_link

            category = get_book_category(book_url) if fetch_category else "Not fetched"

            all_books.append({
                "Title": title,
                "Price (£)": price,
                "Availability": availability,
                "Rating (1-5)": rating,
                "Category": category
            })

        print(f"Scraped page {page}/{max_pages} — {len(articles)} books")
        time.sleep(0.3)  # be polite to the server

    return pd.DataFrame(all_books)


if __name__ == "__main__":
    # fetch_category=True makes ~1000 extra requests (one per book) and can take
    # several minutes. Set it to False for a much faster run if you don't need
    # the Category column for your analysis (Task 2/3 charts will just skip it).
    df = scrape_all_books(fetch_category=True)
    df.to_csv("books_data.csv", index=False)
    print(f"\nDone. Saved {len(df)} books to books_data.csv")

"""
CodeAlpha Data Analytics Internship
Task 2: Exploratory Data Analysis (EDA)
Input: books_data.csv (produced by task1_web_scraping.py)

What this script does:
1. Loads the scraped dataset and inspects structure/data types
2. Cleans data & checks for missing values / duplicates
3. Answers a few meaningful questions about the dataset:
   - How is price distributed across the catalogue?
   - Which categories are most expensive on average?
   - Is there a relationship between rating and price?
   - How many books are in stock vs out of stock?
4. Saves visualizations as PNG files + a short text summary (insights.txt)

Run:
    pip install pandas matplotlib seaborn
    python task2_eda_analysis.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

INPUT_FILE = "books_data.csv"   # swap for books_data_sample.csv to test without scraping


def load_and_clean(path):
    df = pd.read_csv(path)
    print("Shape:", df.shape)
    print("\nData types:\n", df.dtypes)
    print("\nMissing values:\n", df.isnull().sum())
    print("\nDuplicate rows:", df.duplicated().sum())

    df = df.drop_duplicates()
    df["Availability"] = df["Availability"].str.strip()
    return df


def run_eda(df):
    insights = []

    # 1. Price distribution
    plt.figure(figsize=(8, 5))
    sns.histplot(df["Price (£)"], bins=20, kde=True, color="steelblue")
    plt.title("Distribution of Book Prices")
    plt.xlabel("Price (£)")
    plt.tight_layout()
    plt.savefig("price_distribution.png", dpi=150)
    plt.close()
    insights.append(
        f"Average price: £{df['Price (£)'].mean():.2f} | "
        f"Median: £{df['Price (£)'].median():.2f} | "
        f"Range: £{df['Price (£)'].min():.2f} - £{df['Price (£)'].max():.2f}"
    )

    # 2. Average price by category (top 10)
    avg_price_cat = df.groupby("Category")["Price (£)"].mean().sort_values(ascending=False).head(10)
    plt.figure(figsize=(9, 5))
    sns.barplot(x=avg_price_cat.values, y=avg_price_cat.index, palette="viridis")
    plt.title("Top 10 Categories by Average Price")
    plt.xlabel("Average Price (£)")
    plt.tight_layout()
    plt.savefig("avg_price_by_category.png", dpi=150)
    plt.close()
    insights.append(f"Most expensive category on average: {avg_price_cat.index[0]} (£{avg_price_cat.iloc[0]:.2f})")

    # 3. Rating vs price
    plt.figure(figsize=(8, 5))
    sns.boxplot(x="Rating (1-5)", y="Price (£)", data=df, palette="coolwarm")
    plt.title("Price Distribution by Rating")
    plt.tight_layout()
    plt.savefig("rating_vs_price.png", dpi=150)
    plt.close()
    corr = df["Rating (1-5)"].corr(df["Price (£)"])
    insights.append(f"Correlation between rating and price: {corr:.3f} (weak/no linear relationship expected)")

    # 4. Stock availability
    stock_counts = df["Availability"].value_counts()
    plt.figure(figsize=(6, 6))
    plt.pie(stock_counts, labels=stock_counts.index, autopct="%1.1f%%",
            colors=["#4CAF50", "#F44336"], startangle=90)
    plt.title("In Stock vs Out of Stock")
    plt.tight_layout()
    plt.savefig("stock_availability.png", dpi=150)
    plt.close()
    insights.append(f"Stock split: {stock_counts.to_dict()}")

    # 5. Rating distribution
    plt.figure(figsize=(7, 5))
    sns.countplot(x="Rating (1-5)", data=df, hue="Rating (1-5)",
                  palette="magma", legend=False)
    plt.title("Rating Distribution")
    plt.tight_layout()
    plt.savefig("rating_distribution.png", dpi=150)
    plt.close()
    most_common_rating = df["Rating (1-5)"].mode()[0]
    insights.append(f"Most common rating: {most_common_rating} stars")

    return insights


if __name__ == "__main__":
    df = load_and_clean(INPUT_FILE)
    insights = run_eda(df)

    with open("insights.txt", "w") as f:
        f.write("EDA Insights — CodeAlpha Data Analytics Task\n")
        f.write("=" * 45 + "\n\n")
        for i, line in enumerate(insights, 1):
            f.write(f"{i}. {line}\n")

    print("\nEDA complete. Charts saved as PNG files, summary saved to insights.txt")
    for line in insights:
        print("-", line)

"""
CodeAlpha Data Analytics Internship
Task 3: Data Visualization
Input: books_data.csv (from task1_web_scraping.py)

What this script does:
- Builds a single, polished multi-panel DASHBOARD (not just separate exploratory
  plots like Task 2) meant for a portfolio / LinkedIn post.
- Focuses on storytelling: each panel has a clear takeaway, consistent color
  theme, and readable labels — designed to be screenshot-shared, not just
  analyzed.
- Saves: dashboard.png (main portfolio piece) + top_categories.png (bonus
  standalone chart)

Run:
    pip install pandas matplotlib seaborn
    python task3_data_visualization.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

INPUT_FILE = "books_data.csv"   # swap for books_data_sample.csv to test without scraping

THEME_COLOR = "#2E5EAA"
ACCENT_COLOR = "#F2A541"
sns.set_style("whitegrid")
plt.rcParams["font.family"] = "sans-serif"


def build_dashboard(df):
    fig = plt.figure(figsize=(15, 10))
    fig.suptitle("Books.ToScrape Catalogue — A Data Story",
                 fontsize=20, fontweight="bold", y=0.98)
    fig.text(0.5, 0.945,
              "1,000 books analyzed across price, rating, category, and stock availability",
              ha="center", fontsize=11, color="gray")

    gs = gridspec.GridSpec(2, 3, figure=fig, wspace=0.35, hspace=0.4,
                            top=0.88, bottom=0.08, left=0.06, right=0.97)

    # Panel 1: Price distribution
    ax1 = fig.add_subplot(gs[0, 0])
    sns.histplot(df["Price (£)"], bins=18, color=THEME_COLOR, kde=True, ax=ax1)
    ax1.set_title("Where do prices cluster?", fontweight="bold")
    ax1.set_xlabel("Price (£)")

    # Panel 2: Top categories by average price
    ax2 = fig.add_subplot(gs[0, 1:])
    top_cats = df.groupby("Category")["Price (£)"].mean().sort_values(ascending=False).head(8)
    bars = ax2.barh(top_cats.index[::-1], top_cats.values[::-1], color=THEME_COLOR)
    bars[-1].set_color(ACCENT_COLOR)  # highlight the top category
    ax2.set_title("Which categories cost the most, on average?", fontweight="bold")
    ax2.set_xlabel("Average Price (£)")

    # Panel 3: Rating distribution
    ax3 = fig.add_subplot(gs[1, 0])
    rating_counts = df["Rating (1-5)"].value_counts().sort_index()
    ax3.bar(rating_counts.index, rating_counts.values, color=THEME_COLOR)
    ax3.set_title("How are books rated?", fontweight="bold")
    ax3.set_xlabel("Star Rating")
    ax3.set_xticks([1, 2, 3, 4, 5])

    # Panel 4: Rating vs price
    ax4 = fig.add_subplot(gs[1, 1])
    sns.boxplot(x="Rating (1-5)", y="Price (£)", data=df, ax=ax4, color=THEME_COLOR)
    ax4.set_title("Does rating affect price?", fontweight="bold")

    # Panel 5: Stock availability
    ax5 = fig.add_subplot(gs[1, 2])
    stock_counts = df["Availability"].value_counts()
    ax5.pie(stock_counts, labels=stock_counts.index, autopct="%1.0f%%",
            colors=[THEME_COLOR, ACCENT_COLOR], startangle=90,
            textprops={"fontsize": 9})
    ax5.set_title("In stock vs out of stock", fontweight="bold")

    fig.text(0.5, 0.02,
              "Source: books.toscrape.com  |  CodeAlpha Data Analytics Internship — Task 3",
              ha="center", fontsize=9, color="gray")

    plt.savefig("dashboard.png", dpi=180, bbox_inches="tight")
    plt.close()


def build_bonus_chart(df):
    """A single clean, presentation-ready chart for social/portfolio use."""
    top_cats = df["Category"].value_counts().head(10)

    plt.figure(figsize=(9, 6))
    bars = plt.barh(top_cats.index[::-1], top_cats.values[::-1], color=THEME_COLOR)
    bars[-1].set_color(ACCENT_COLOR)
    plt.title("Top 10 Most-Stocked Book Categories", fontsize=14, fontweight="bold")
    plt.xlabel("Number of Books")
    sns.despine(left=True, bottom=True)
    plt.tight_layout()
    plt.savefig("top_categories.png", dpi=180)
    plt.close()


if __name__ == "__main__":
    df = pd.read_csv(INPUT_FILE)
    build_dashboard(df)
    build_bonus_chart(df)
    print("Saved dashboard.png and top_categories.png")